name: curl
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - pytorch
  - cudatoolkit
  - absl-py
  - spyder
  - pyparsing
  - pillow
  - opencv
  - plotly
  - kornia
  - tqdm
  - gym
  - scikit-image
